### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by qwerooo** [geeeeeeeek/java_video#1]
可以增加用视频链接进行播放。

**Comment by geeeeeeeek** [comment]
> 可以增加用视频链接进行播放。

好建议。

**Comment by Lin-Buji** [comment]
> > 可以增加用视频链接进行播放。
> 
> 好建议。

可不可以补充上传一个sql文件~

**Comment by kirinmin** [comment]
> > > 可以增加用视频链接进行播放。
> > 
> > 
> > 好建议。
> 
> 可不可以补充上传一个sql文件~

感觉悬 估计数据库是要买的
